### ISSUE TITLE
Project build fails with error after adding kmpauth dependency (ios linking problem)

### ISSUE THREAD

**Issue by Dosssik** [mirzemehdi/KMPAuth#10] opened 2024-03-09 22:50 UTC
Hey, was trying to use the KMPAuth library but faced a problem with the iOS platform (android builds and works):

With the following build script:
```
commonMain.dependencies { 
            implementation(libs.kmpAuth.google) // v 1.2.0
        }
```
the iOS build fails with the following error:
```
** BUILD FAILED **
ld: warning: Could not find or use auto-linked framework 'GoogleSignIn'

ld: warning: Could not find or use auto-linked framework 'Symbols'
Undefined symbols for architecture arm64:

  "_OBJC_CLASS_$_GIDSignIn", referenced from:
The following build commands failed:
      objc-class-ref in composeApp(libio.github.mirzemehdi:kmpauth-google-cache.a.o)
ld: symbol(s) not found for architecture arm64
	Ld /(PROJECT_PATH)/build/ios/Debug-iphonesimulator/(PROJECT_NAME).app/(PROJECT_NAME) normal (in target 'iosApp' from project 'iosApp')
clang: error: linker command failed with exit code 1 (use -v to see invocation)
(1 failure)
```
Google Sign-In is added via Swift Package manager (tried with cocoapods, same).

---

If I add `implementation(libs.kmpAuth.firebase)` it fails with similar error:
```
ld: warning: Could not find or use auto-linked framework 'Symbols'
ld: warning: Could not find or use auto-linked framework 'FirebaseCore'
ld: warning: Could not find or use auto-linked framework 'FirebaseAuth'
ld: warning: Could not find or use auto-linked framework 'GoogleSignIn'
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FIRActionCodeInfo", referenced from:
      objc-class-ref in composeApp(libdev.gitlive:firebase-auth-cache.a.o)
  "_OBJC_CLASS_$_FIRActionCodeSettings", referenced from:
      objc-class-ref in composeApp(libdev.gitlive:firebase-auth-cache.a.o)
  "_OBJC_CLASS_$_FIRApp", referenced from:
      objc-class-ref in composeApp(libdev.gitlive:firebase-app-cache.a.o)
  "_OBJC_CLASS_$_FIRAuth", referenced from:
      objc-class-ref in composeApp(libdev.gitlive:firebase-auth-cache.a.o)
      objc-class-ref in composeApp(libio.github.mirzemehdi:kmpauth-firebase-cache.a.o)
  "_OBJC_CLASS_$_FIRAuthDataResult", referenced from:
      objc-class-ref in composeApp(libdev.gitlive:firebase-auth-cache.a.o)
  "_OBJC_CLASS_$_FIRAuthTokenResult", referenced from:
      objc-class-ref in composeApp(libdev.gitlive:firebase-auth-cache.a.o)
  "_OBJC_CLASS_$_FIREmailAuthProvider", referenced from:
      objc-class-ref in composeApp(libdev.gitlive:firebase-auth-cache.a.o)
  "_OBJC_CLASS_$_FIRFacebookAuthProvider", referenced from:
      objc-class-ref in composeApp(libdev.gitlive:firebase-auth-cache.a.o)
  "_OBJC_CLASS_$_FIRGitHubAuthProvider", referenced from:
      objc-class-ref in composeApp(libdev.gitlive:firebase-auth-cache.a.o)
  "_OBJC_CLASS_$_FIRGoogleAuthProvider", referenced from:
      objc-class-ref in composeApp(libdev.gitlive:firebase-auth-cache.a.o)
  "_OBJC_CLASS_$_FIRMultiFactorInfo", referenced from:
      objc-class-ref in composeApp(libdev.gitlive:firebase-auth-cache.a.o)
  "_OBJC_CLASS_$_FIRMultiFactorSession", referenced from:
      objc-class-ref in composeApp(libdev.gitlive:firebase-auth-cache.a.o)
  "_OBJC_CLASS_$_FIROAuthProvider", referenced from:
      objc-class-ref in composeApp(libdev.gitlive:firebase-auth-cache.a.o)
      objc-class-ref in composeApp(libio.github.mirzemehdi:kmpauth-firebase-cache.a.o)
  "_OBJC_CLASS_$_FIROptions", referenced from:
      objc-class-ref in composeApp(libdev.gitlive:firebase-app-cache.a.o)
  "_OBJC_CLASS_$_FIRPhoneAuthProvider", referenced from:
      objc-class-ref in composeApp(libdev.gitlive:firebase-auth-cache.a.o)
  "_OBJC_CLASS_$_FIRTwitterAuthProvider", referenced from:
      objc-class-ref in composeApp(libdev.gitlive:firebase-auth-cache.a.o)
  "_OBJC_CLASS_$_FIRUser", referenced from:
      objc-class-ref in composeApp(libdev.gitlive:firebase-auth-cache.a.o)
  "_OBJC_CLASS_$_GIDSignIn", referenced from:
      objc-class-ref in composeApp(libio.github.mirzemehdi:kmpauth-google-cache.a.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **
```

Any ideas on how to fix it?

**Comment by mirzemehdi** [comment] 2024-03-10 13:59
Duplicate of https://github.com/mirzemehdi/KMPAuth/issues/8

**Comment by mirzemehdi** [comment] 2024-03-10 14:00
@Dosssik Usually adding Firebase and GoogleSignIn from Swift Package Manager would help. Is it possible to link to source code?

**Comment by mirzemehdi** [comment] 2024-05-13 22:50
Not reproducible. Closing this issue due to inactivity. If this is still an issue or need a help, please feel free to reopen the issue and provide additional context or updates. Thank you.

**Closed by mirzemehdi** 2024-05-13 22:50 UTC
Labels: duplicate

**Comment by shalva97** [comment] 2024-11-27 19:09
@Dosssik Hi. have you solved it? I have similar issue

```
ld: warning: search path '/Users/Giorgi_Shalvashvili/IdeaProjects/catchclicker/iosApp/../shared/build/xcode-frameworks/Debug/iphonesimulator18.1' not found
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
ld: warning: Could not find or use auto-linked framework 'FirebaseAuth': framework 'FirebaseAuth' not found
ld: warning: Could not find or use auto-linked framework 'FirebaseAuthInterop': framework 'FirebaseAuthInterop' not found
ld: warning: Could not find or use auto-linked framework 'FirebaseCore': framework 'FirebaseCore' not found
ld: warning: Could not find or use auto-linked framework 'GoogleSignIn': framework 'GoogleSignIn' not found
ld: warning: Could not parse or use implicit file '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/SwiftUICore.framework/SwiftUICore.tbd': cannot link directly with 'SwiftUICore' because product being built is not an allowed client of it
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FIRAuth", referenced from:
       in ComposeApp[2819](libdev.gitlive:firebase-auth-cache.a.o)
  "_OBJC_CLASS_$_FIROAuthProvider", referenced from:
       in ComposeApp[2819](libdev.gitlive:firebase-auth-cache.a.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld /Users/Giorgi_Shalvashvili/IdeaProjects/catchclicker/build/ios/Debug-iphonesimulator/CatchClicker.app/CatchClicker.debug.dylib normal (in target 'iosApp' from project 'iosApp')
	Building project iosApp with scheme iosApp and configuration Debug
(2 failures)
```

**Comment by long06031999** [comment] 2024-11-30 06:41
@shalva97 I have similar issue, any solution ?

**Comment by shalva97** [comment] 2024-11-30 12:03
Hard to say I tried so many things. Probably it started to work after I tried to add https://github.com/firebase/firebase-ios-sdk dependency from xcode
